[package]
name = "numo"
version = "0.1.0"
edition = "2021"

[dependencies]
## core
artemis-core = { path = "../../crates/artemis-core" }
numo-arb = { path = "../../crates/strategies/numo-arb" }

## eth
ethers.workspace = true
ethers-signers.workspace = true

## async
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
async-trait = "0.1.64"

## cli
clap = { version = "4.2", features = ["derive", "env"] }
dotenv = "0.15"

## logging
tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

## misc
anyhow = "1.0.70"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
